# Generated by Django 4.0.6 on 2023-01-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BooK',
            fields=[
                ('bookId', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('bookName', models.CharField(max_length=50, null=True)),
                ('AuthorName', models.CharField(max_length=50, null=True)),
                ('rate', models.FloatField(null=True)),
                ('startDate', models.DateField(null=True)),
                ('endDate', models.DateField(null=True)),
                ('status', models.CharField(max_length=50, null=True)),
                ('bookImage', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
